apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/secret.yaml
  - ../../deployments/core-deployments.yaml
  - ../../services/core-services.yaml
  - ../../hpa/core-hpa.yaml
  - ../../observability/stack.yaml
  - sealed-secret.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - path: replicas-patch.yaml
  - path: resource-patch.yaml
