apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../deployments/core-deployments.yaml
  - ../../services/core-services.yaml
  - ../../hpa/core-hpa.yaml
  - ../../observability/stack.yaml
  - sealed-secret.yaml
patchesStrategicMerge:
  - configmap-patch.yaml
  - replicas-patch.yaml
