version: "3.9"

services:
  meeting-api:
    build: ../demoRecordAUDIOMID/meeting-service
    env_file: .env

  processing-api:
    build: ../demoRecordAUDIOMID/processing-service
    env_file: .env

  ai-api:
    build: ../demoRecordAUDIOMID/ai-service
    env_file: .env

  web:
    build: ../FE-Audiomind

  db:
    image: postgres:15

  redis:
    image: redis:7
