name: audiomind-prod

services:
  meeting-api:
    environment:
      SPRING_PROFILES_ACTIVE: production
      OTEL_SDK_DISABLED: "true"
      OTEL_ENABLED: "false"

  processing-api:
    environment:
      SPRING_PROFILES_ACTIVE: production
      OTEL_SDK_DISABLED: "true"
      OTEL_ENABLED: "false"

  user-api:
    environment:
      SPRING_PROFILES_ACTIVE: production
      OTEL_SDK_DISABLED: "true"
      OTEL_ENABLED: "false"

  ai-api:
    environment:
      APP_ENV: production
      OTEL_SDK_DISABLED: "true"

  celery-beat:
    environment:
      APP_ENV: production
      OTEL_SDK_DISABLED: "true"

  celery-worker:
    environment:
      APP_ENV: production
      OTEL_SDK_DISABLED: "true"
