export interface ITTermDefinition {
  canonical: string
  aliases?: string[]
  caseSensitive?: boolean
}

export const DEFAULT_IT_TERMS: ITTermDefinition[] = [
  // Web/API
  { canonical: 'REST API' },
  { canonical: 'GraphQL' },
  { canonical: 'WebSocket latency' },
  { canonical: 'WebSocket', aliases: ['web socket'] },
  { canonical: 'rate limit' },
  { canonical: 'middleware' },
  { canonical: 'endpoint' },
  { canonical: 'route' },
  { canonical: 'payload' },
  { canonical: 'header' },
  { canonical: 'cookie' },
  { canonical: 'webhook' },
  { canonical: 'authentication', aliases: ['auth'] },
  { canonical: 'authorization' },
  { canonical: 'API', caseSensitive: true },
  { canonical: 'HTTP', caseSensitive: true },
  { canonical: 'HTTPS', caseSensitive: true },
  { canonical: 'CORS', caseSensitive: true },
  { canonical: 'CRUD', caseSensitive: true },
  { canonical: 'JSON', caseSensitive: true },
  { canonical: 'XML', caseSensitive: true },
  { canonical: 'JWT', caseSensitive: true },
  { canonical: 'OAuth', caseSensitive: true },

  // Database/Data
  { canonical: 'database migration' },
  { canonical: 'database', aliases: ['db'] },
  { canonical: 'NoSQL', caseSensitive: true },
  { canonical: 'query' },
  { canonical: 'schema' },
  { canonical: 'migration' },
  { canonical: 'index' },
  { canonical: 'transaction' },
  { canonical: 'repository', aliases: ['repo'] },
  { canonical: 'cache' },
  { canonical: 'Redis', caseSensitive: true },
  { canonical: 'MongoDB', caseSensitive: true },
  { canonical: 'PostgreSQL', caseSensitive: true },
  { canonical: 'MySQL', caseSensitive: true },
  { canonical: 'ORM', caseSensitive: true },
  { canonical: 'backup' },
  { canonical: 'replication' },
  { canonical: 'SQL', caseSensitive: true },

  // DevOps/Cloud
  { canonical: 'GitHub Actions' },
  { canonical: 'CI pipeline' },
  { canonical: 'CD pipeline' },
  { canonical: 'CI/CD', caseSensitive: true },
  { canonical: 'pipeline' },
  { canonical: 'workflow' },
  { canonical: 'job' },
  { canonical: 'runner' },
  { canonical: 'deployment' },
  { canonical: 'deploy' },
  { canonical: 'staging' },
  { canonical: 'production' },
  { canonical: 'Docker' },
  { canonical: 'containers', aliases: ['container'] },
  { canonical: 'Kubernetes' },
  { canonical: 'K8s', caseSensitive: true },
  { canonical: 'pod' },
  { canonical: 'namespace' },
  { canonical: 'cluster' },
  { canonical: 'Helm' },
  { canonical: 'cloud' },
  { canonical: 'AWS', caseSensitive: true },
  { canonical: 'Azure' },
  { canonical: 'Google Cloud' },

  // Programming/Software Engineering
  { canonical: 'frontend' },
  { canonical: 'backend' },
  { canonical: 'full-stack' },
  { canonical: 'source code' },
  { canonical: 'codebase' },
  { canonical: 'function' },
  { canonical: 'class' },
  { canonical: 'component' },
  { canonical: 'module' },
  { canonical: 'microservice' },
  { canonical: 'architecture' },
  { canonical: 'design pattern' },
  { canonical: 'dependency' },
  { canonical: 'package' },
  { canonical: 'library' },
  { canonical: 'framework' },
  { canonical: 'debug' },
  { canonical: 'exception' },
  { canonical: 'error handling' },
  { canonical: 'integration test' },
  { canonical: 'unit test' },
  { canonical: 'end-to-end test' },
  { canonical: 'E2E test', caseSensitive: true },

  // Cybersecurity
  { canonical: 'cybersecurity' },
  { canonical: 'information security' },
  { canonical: 'vulnerability' },
  { canonical: 'malware' },
  { canonical: 'phishing' },
  { canonical: 'firewall' },
  { canonical: 'encryption' },
  { canonical: 'hash' },
  { canonical: 'access control' },
  { canonical: 'permission' },
  { canonical: 'RBAC', caseSensitive: true },
  { canonical: 'MFA', caseSensitive: true },
  { canonical: '2FA', caseSensitive: true },
  { canonical: 'XSS', caseSensitive: true },
  { canonical: 'CSRF', caseSensitive: true },
  { canonical: 'DDoS', caseSensitive: true },
  { canonical: 'SQL injection', caseSensitive: true },

  // AI/ML
  { canonical: 'AI agent', caseSensitive: true },
  { canonical: 'AI agents', caseSensitive: true },
  { canonical: 'AI labs', caseSensitive: true },
  { canonical: 'OpenAI' },
  { canonical: 'Anthropic' },
  { canonical: 'Google' },
  { canonical: 'Gemini' },
  { canonical: 'ChatGPT' },
  { canonical: 'large language model' },
  { canonical: 'machine learning' },
  { canonical: 'deep learning' },
  { canonical: 'embedding' },
  { canonical: 'vector' },
  { canonical: 'fine-tuning' },
  { canonical: 'inference' },
  { canonical: 'training' },
  { canonical: 'dataset' },
  { canonical: 'AI', caseSensitive: true },
  { canonical: 'LLM', caseSensitive: true },
  { canonical: 'RAG', caseSensitive: true },

  // Vietnamese IT/domain
  { canonical: 'mạng máy tính và truyền thông' },
  { canonical: 'bảo mật hệ thống thông tin' },
  { canonical: 'kiểm duyệt chất lượng phần mềm' },
  { canonical: 'phân tích thiết kế hệ thống' },
  { canonical: 'Công nghệ thông tin', aliases: ['công nghệ tt'] },
  { canonical: 'công nghệ phần mềm' },
  { canonical: 'hệ thống thông tin' },
  { canonical: 'khoa học máy tính' },
  { canonical: 'kỹ thuật máy tính' },
  { canonical: 'kỹ thuật phần mềm' },
  { canonical: 'an toàn thông tin' },
  { canonical: 'mạng máy tính' },
  { canonical: 'quản trị mạng' },
  { canonical: 'lập trình viên' },
  { canonical: 'phần mềm' },
  { canonical: 'phần cứng' },
  { canonical: 'truyền thông' },
  { canonical: 'lập trình' },
  { canonical: 'bảo mật' },
  { canonical: 'CNTT', caseSensitive: true },
  { canonical: 'IT', caseSensitive: true },

  // Vietnamese technical translations
  { canonical: 'giao diện lập trình ứng dụng' },
  { canonical: 'điểm cuối' },
  { canonical: 'yêu cầu HTTP', caseSensitive: true },
  { canonical: 'phản hồi HTTP', caseSensitive: true },
  { canonical: 'xác thực' },
  { canonical: 'phân quyền' },
  { canonical: 'mã thông báo' },
  { canonical: 'phiên đăng nhập' },
  { canonical: 'phần mềm trung gian' },
  { canonical: 'cơ sở dữ liệu' },
  { canonical: 'truy vấn' },
  { canonical: 'lược đồ' },
  { canonical: 'di trú cơ sở dữ liệu' },
  { canonical: 'bộ nhớ đệm' },
  { canonical: 'sao lưu' },
  { canonical: 'nhân bản dữ liệu' },
  { canonical: 'quản lý dữ liệu' },
  { canonical: 'tích hợp liên tục' },
  { canonical: 'triển khai liên tục' },
  { canonical: 'đường ống CI/CD', caseSensitive: true },
  { canonical: 'quy trình tự động' },
  { canonical: 'bản dựng' },
  { canonical: 'vùng chứa' },
  { canonical: 'cụm' },
  { canonical: 'dịch vụ Kubernetes', caseSensitive: true },
  { canonical: 'không gian tên' },
  { canonical: 'điện toán đám mây' },
  { canonical: 'mã nguồn' },
  { canonical: 'cơ sở mã' },
  { canonical: 'hàm' },
  { canonical: 'lớp' },
  { canonical: 'thành phần' },
  { canonical: 'mô-đun' },
  { canonical: 'vi dịch vụ' },
  { canonical: 'kiến trúc' },
  { canonical: 'mẫu thiết kế' },
  { canonical: 'phụ thuộc' },
  { canonical: 'thư viện' },
  { canonical: 'khung làm việc' },
  { canonical: 'gỡ lỗi' },
  { canonical: 'ngoại lệ' },
  { canonical: 'xử lý lỗi' },
  { canonical: 'kiểm thử đơn vị' },
  { canonical: 'kiểm thử tích hợp' },
  { canonical: 'kiểm thử đầu cuối' },
  { canonical: 'an ninh mạng' },
  { canonical: 'lỗ hổng bảo mật' },
  { canonical: 'mã độc' },
  { canonical: 'lừa đảo trực tuyến' },
  { canonical: 'tường lửa' },
  { canonical: 'mã hóa' },
  { canonical: 'hàm băm' },
  { canonical: 'kiểm soát truy cập' },
  { canonical: 'quyền truy cập' },
  { canonical: 'vai trò' },
  { canonical: 'xác thực đa yếu tố' },
  { canonical: 'xác thực hai yếu tố' },
  { canonical: 'tấn công từ chối dịch vụ' },
  { canonical: 'chèn mã SQL', caseSensitive: true },
  { canonical: 'trí tuệ nhân tạo' },
  { canonical: 'tác nhân AI', caseSensitive: true },
  { canonical: 'mô hình ngôn ngữ lớn' },
  { canonical: 'học máy' },
  { canonical: 'học sâu' },
  { canonical: 'nhúng' },
  { canonical: 'truy xuất tăng cường' },
  { canonical: 'tinh chỉnh mô hình' },
  { canonical: 'suy luận' },
  { canonical: 'huấn luyện' },
  { canonical: 'tập dữ liệu' },
  { canonical: 'Internet', aliases: ['internet'] },
  { canonical: 'OpenAPI' },
  { canonical: 'contract' },
]

export const CAUTIOUS_IT_TERMS: string[] = [
  'test',
  'log',
  'bug',
  'error',
  'build',
  'server',
  'client',
  'request',
  'response',
  'branch',
  'commit',
  'merge',
  'token',
  'session',
  'model',
  'prompt',
  'service',
  'data',
  'network',
  'security',
  'agent',
  'lab',
  'công nghệ',
  'thông tin',
  'máy tính',
  'mạng',
  'dữ liệu',
  'hệ thống',
  'dịch vụ',
  'mô hình',
  'kiểm thử',
  'lỗi',
  'xây dựng',
  'triển khai',
]
