/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create meeting */
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meeting */
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update meeting result */
        put: operations["updateMeetingResult"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create scheduled meeting for Google Calendar linking */
        post: operations["createScheduledMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/google/calendar-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Google Calendar event for meeting */
        post: operations["createGoogleCalendarEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll Google Calendar creation status */
        get: operations["getGoogleCalendarStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/google/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Google calendars for linked account */
        get: operations["listGoogleCalendars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/google/meet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create quick Google Meet */
        post: operations["createQuickGoogleMeet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meetingId}/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List speaker display profiles */
        get: operations["listMeetingSpeakerProfiles"];
        /** Upsert speaker display profiles */
        put: operations["upsertMeetingSpeakerProfiles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meetingId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meeting tasks */
        get: operations["listMeetingTasks"];
        put?: never;
        /** Create meeting task */
        post: operations["createMeetingTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List study folders */
        get: operations["listStudyFolders"];
        put?: never;
        /** Create study folder */
        post: operations["createStudyFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-folders/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get study folder tree with subjects */
        get: operations["getStudyFolderTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-folders/{folderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get study folder by id */
        get: operations["getStudyFolder"];
        put?: never;
        post?: never;
        /** Delete study folder */
        delete: operations["deleteStudyFolder"];
        options?: never;
        head?: never;
        /** Update study folder */
        patch: operations["updateStudyFolder"];
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subjects */
        get: operations["listSubjects"];
        put?: never;
        /** Create subject */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subjectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subject detail */
        get: operations["getSubject"];
        put?: never;
        post?: never;
        /** Archive subject */
        delete: operations["archiveSubject"];
        options?: never;
        head?: never;
        /** Update subject */
        patch: operations["updateSubject"];
        trace?: never;
    };
    "/subjects/{subjectId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings for subject */
        get: operations["listSubjectMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create realtime meeting */
        post: operations["createRealtimeMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload meeting audio */
        post: operations["uploadMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/unclassified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List unclassified meetings */
        get: operations["listUnclassifiedMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meetingId}/subject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign or remove meeting subject */
        patch: operations["assignMeetingSubject"];
        trace?: never;
    };
    "/internal/subjects/{subjectId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Internal subject membership page (service-to-service)
         * @description Authenticated with X-Internal-Service-Token and scoped by X-Owner-User-Id. Used by AI study workers; does not accept user JWT.
         */
        get: operations["listInternalSubjectMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meeting: {
            id: string;
            status: string;
            transcript?: string | null;
            summary?: string | null;
        };
        ScheduledMeetingCreate: {
            title: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
            timeZone: string;
            language?: string;
        };
        ScheduledMeeting: {
            /** Format: int64 */
            id: number;
            title: string;
            status: string;
            /** Format: date-time */
            scheduledStartAt?: string;
            /** Format: date-time */
            scheduledEndAt?: string;
            scheduledTimezone?: string;
        };
        GoogleCalendarEventCreate: {
            startDateTime: string;
            endDateTime: string;
            timeZone: string;
            attendees?: string[];
        };
        GoogleCalendarStatus: {
            /** Format: int64 */
            meetingId: number;
            /** @enum {string} */
            creationStatus: "not_created" | "creating" | "success" | "failed";
            conferenceStatus: string;
            googleCalendarEventId?: string | null;
            meetUri?: string | null;
            hangoutLink?: string | null;
            errorCode?: string | null;
        };
        MeetingResultUpdate: {
            transcript: string;
            summary: string;
        };
        CreateStudyFolderRequest: {
            name: string;
            color?: string | null;
            /** Format: int64 */
            parentFolderId?: number | null;
        };
        UpdateStudyFolderRequest: {
            name?: string;
            color?: string | null;
            /** Format: int64 */
            parentFolderId?: number | null;
        };
        StudyFolderResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            ownerUserId?: number;
            /** Format: int64 */
            parentFolderId?: number | null;
            name: string;
            color?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
            /** Format: int64 */
            subjectCount?: number;
        };
        SubjectSummaryResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            code?: string | null;
            semester?: string | null;
            color?: string | null;
            /** Format: int64 */
            folderId?: number | null;
            /** Format: date-time */
            archivedAt?: string | null;
            /** Format: int64 */
            meetingCount?: number;
        };
        StudyFolderTreeNode: {
            /** Format: int64 */
            id: number;
            name: string;
            color?: string | null;
            /** Format: int64 */
            parentFolderId?: number | null;
            children?: components["schemas"]["StudyFolderTreeNode"][];
            subjects?: components["schemas"]["SubjectSummaryResponse"][];
        };
        StudyFolderTreeResponse: {
            folders?: components["schemas"]["StudyFolderTreeNode"][];
            rootSubjects?: components["schemas"]["SubjectSummaryResponse"][];
        };
        CreateSubjectRequest: {
            name: string;
            code?: string | null;
            semester?: string | null;
            description?: string | null;
            color?: string | null;
            /** Format: int64 */
            folderId?: number | null;
        };
        UpdateSubjectRequest: {
            name?: string;
            code?: string | null;
            semester?: string | null;
            description?: string | null;
            color?: string | null;
            /** Format: int64 */
            folderId?: number | null;
        };
        SubjectResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            ownerUserId?: number;
            /** Format: int64 */
            folderId?: number | null;
            name: string;
            code?: string | null;
            semester?: string | null;
            description?: string | null;
            color?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            archivedAt?: string | null;
            /** Format: int64 */
            meetingCount?: number;
        };
        SubjectDetailResponse: {
            subject: components["schemas"]["SubjectResponse"];
        };
        SubjectMeetingResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            status: string;
            language?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            subjectId?: number | null;
        };
        PageMeta: {
            items: unknown[];
            /** Format: int64 */
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        SubjectPageResponse: {
            items: components["schemas"]["SubjectResponse"][];
            /** Format: int64 */
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        SubjectMeetingPageResponse: {
            items: components["schemas"]["SubjectMeetingResponse"][];
            /** Format: int64 */
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        MeetingEntity: {
            /** Format: int64 */
            id: number;
            title: string;
            audioPath?: string;
            originalFileName?: string | null;
            /** Format: int64 */
            ownerUserId?: number | null;
            /** Format: int64 */
            subjectId?: number | null;
            /** Format: date-time */
            createdAt?: string;
            language?: string | null;
            /** Format: int64 */
            fileSize?: number | null;
            status?: string | null;
            /** Format: date-time */
            scheduledStartAt?: string | null;
            /** Format: date-time */
            scheduledEndAt?: string | null;
            scheduledTimezone?: string | null;
            sharedWithMe?: boolean | null;
        };
        MeetingPageResponse: {
            items: components["schemas"]["MeetingEntity"][];
            /** Format: int64 */
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        CreateRealtimeMeetingRequest: {
            title?: string;
            language?: string;
            /** Format: int64 */
            subjectId?: number | null;
        };
        MeetingUploadResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            audioPath: string;
            /** Format: date-time */
            createdAt?: string;
            originalFileName?: string | null;
            /** Format: int64 */
            ownerUserId?: number | null;
            language?: string | null;
            /** Format: int64 */
            fileSize?: number | null;
            status?: string | null;
            /** Format: int64 */
            subjectId?: number | null;
            duplicate?: boolean;
            reused?: boolean;
            /** Format: int64 */
            existingMeetingId?: number | null;
            source?: string;
        };
        AssignMeetingSubjectRequest: {
            /** Format: int64 */
            subjectId?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
        };
    };
    updateMeetingResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingResultUpdate"];
            };
        };
        responses: {
            /** @description Updated meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
        };
    };
    createScheduledMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledMeetingCreate"];
            };
        };
        responses: {
            /** @description Scheduled meeting created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledMeeting"];
                };
            };
        };
    };
    createGoogleCalendarEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleCalendarEventCreate"];
            };
        };
        responses: {
            /** @description Calendar link status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCalendarStatus"];
                };
            };
            /** @description Calendar event creation in progress */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCalendarStatus"];
                };
            };
        };
    };
    getGoogleCalendarStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Google Calendar status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCalendarStatus"];
                };
            };
            /** @description Calendar event still being created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCalendarStatus"];
                };
            };
        };
    };
    listGoogleCalendars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar list payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createQuickGoogleMeet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    summary?: string;
                };
            };
        };
        responses: {
            /** @description Meet link created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listMeetingSpeakerProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Speaker profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsertMeetingSpeakerProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    profiles?: {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
        responses: {
            /** @description Updated profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMeetingTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createMeetingTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Created task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listStudyFolders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyFolderResponse"][];
                };
            };
        };
    };
    createStudyFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudyFolderRequest"];
            };
        };
        responses: {
            /** @description Created folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyFolderResponse"];
                };
            };
        };
    };
    getStudyFolderTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyFolderTreeResponse"];
                };
            };
        };
    };
    getStudyFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyFolderResponse"];
                };
            };
        };
    };
    deleteStudyFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyFolderResponse"];
                };
            };
        };
    };
    updateStudyFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudyFolderRequest"];
            };
        };
        responses: {
            /** @description Updated folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyFolderResponse"];
                };
            };
        };
    };
    listSubjects: {
        parameters: {
            query?: {
                folderId?: number;
                search?: string;
                archived?: boolean;
                page?: number;
                pageSize?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectPageResponse"];
                };
            };
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubjectRequest"];
            };
        };
        responses: {
            /** @description Created subject */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
        };
    };
    getSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetailResponse"];
                };
            };
        };
    };
    archiveSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived subject */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
        };
    };
    updateSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubjectRequest"];
            };
        };
        responses: {
            /** @description Updated subject */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
        };
    };
    listSubjectMeetings: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject meetings page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectMeetingPageResponse"];
                };
            };
        };
    };
    createRealtimeMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateRealtimeMeetingRequest"];
            };
        };
        responses: {
            /** @description Created realtime meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingUploadResponse"];
                };
            };
        };
    };
    uploadMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    title: string;
                    /** Format: binary */
                    file: string;
                    language?: string;
                    subjectId?: string;
                };
            };
        };
        responses: {
            /** @description Uploaded meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingUploadResponse"];
                };
            };
        };
    };
    listUnclassifiedMeetings: {
        parameters: {
            query?: {
                search?: string;
                sort?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unclassified meetings page (Map wrapper equivalent to PageResponse) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingPageResponse"];
                };
            };
        };
    };
    assignMeetingSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignMeetingSubjectRequest"];
            };
        };
        responses: {
            /** @description Updated meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingEntity"];
                };
            };
        };
    };
    listInternalSubjectMeetings: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header: {
                "X-Internal-Service-Token": string;
                "X-Owner-User-Id": number;
            };
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged subject meetings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectMeetingPageResponse"];
                };
            };
            /** @description Missing or invalid owner header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or missing internal token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found for owner */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal token not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
