/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/processing/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload audio file for processing */
        post: operations["uploadAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start processing for a meeting */
        post: operations["startProcessing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/status/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get processing status by meeting/job identifier */
        get: operations["getProcessingStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/transcript/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transcript payload by meeting/job identifier (legacy)
         * @deprecated
         * @description Prefer GET /processing/{meetingId}/transcript
         */
        get: operations["getProcessingTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get analysis payload by meeting identifier */
        get: operations["getProcessingAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/transcript/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export saved transcript as readable or raw TXT/CSV */
        get: operations["exportRawTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get saved transcript by meeting identifier */
        get: operations["getMeetingTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/transcript/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search transcript evidence */
        get: operations["searchMeetingTranscriptEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask meeting chatbot with citations */
        post: operations["askMeetingChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/search/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic meeting search */
        post: operations["semanticSearchMeetings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/cross-meeting/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask across meetings */
        post: operations["askCrossMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/action-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get grouped action plan preview */
        get: operations["getMeetingActionPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/action-plan/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export action plan as DOCX */
        get: operations["exportMeetingActionPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/{meetingId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export meeting report as DOCX or PDF */
        get: operations["exportMeetingReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/subjects/{subjectId}/synthesis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current subject synthesis */
        get: operations["getSubjectSynthesis"];
        put?: never;
        /** Prepare or create subject synthesis job */
        post: operations["createSubjectSynthesis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/subjects/{subjectId}/synthesis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subject synthesis status */
        get: operations["getSubjectSynthesisStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/subjects/{subjectId}/synthesis/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force regenerate subject synthesis */
        post: operations["regenerateSubjectSynthesis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/study-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare or create study artifacts */
        post: operations["createStudyArtifacts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/study-artifacts/{artifactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get study artifact by id */
        get: operations["getStudyArtifact"];
        put?: never;
        post?: never;
        /** Soft-delete study artifact */
        delete: operations["deleteStudyArtifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/study-artifacts/{artifactId}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force regenerate one study artifact */
        post: operations["regenerateStudyArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processing/subjects/{subjectId}/study-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List study artifacts for a subject */
        get: operations["listSubjectStudyArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/transcript-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transcript quality policy (Epic 3) */
        get: operations["getTranscriptQualityPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create processing job */
        post: operations["createProcessingJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateJobRequest: {
            meeting_id: string;
        };
        JobResponse: {
            meeting_id: string;
            status: string;
            transcript?: string;
            summary?: string;
        };
        UploadResponse: {
            audio_path: string;
            original_filename: string;
        };
        ProcessStartRequest: {
            /** Format: int64 */
            meeting_id?: number;
            audio_path?: string;
            file_id?: string;
            topic?: string;
            glossary_terms?: string[];
            language?: string;
        };
        ProcessingStartResponse: {
            /** Format: int64 */
            meetingId: number;
            status: string;
            error?: string | null;
            updatedAt?: string | null;
        };
        ProcessingStatusResponse: {
            /** Format: int64 */
            meetingId: number;
            status: string;
            progress: number;
            stage: string;
            error?: string | null;
            updatedAt?: string | null;
        };
        TranscriptPayload: {
            /** Format: int64 */
            meeting_id: number;
            status: string;
            transcripts: {
                [key: string]: unknown;
            }[];
        };
        AnalysisPayload: {
            /** Format: int64 */
            meeting_id: number;
            status: string;
            /** Format: int64 */
            meetingId?: number;
            data?: components["schemas"]["StructuredAnalysis"];
            structuredAnalysis?: components["schemas"]["StructuredAnalysis"];
        } & {
            [key: string]: unknown;
        };
        StructuredAnalysis: {
            summary: string;
            keywords: string[];
            technicalTerms: components["schemas"]["TechnicalTerm"][];
            painPoints: components["schemas"]["PainPoint"][];
            actionItems: string[];
            /** @enum {string} */
            domainMode: "general" | "it" | "business" | "education";
            evidence?: components["schemas"]["EvidenceBlock"];
        };
        EvidenceBlock: {
            matches?: components["schemas"]["AnalysisEvidenceMatch"][];
        };
        AnalysisEvidenceMatch: {
            verificationStatus?: string;
            score?: number;
            snippet?: string;
            speaker?: string;
            startTime?: number;
            endTime?: number;
            dedupeKey?: string;
        };
        TranscriptEvidenceMatch: {
            evidenceId?: string;
            segmentId?: string;
            index?: number;
            speaker?: string;
            startTime?: number;
            endTime?: number;
            text?: string;
            textTruncated?: boolean;
            score?: number;
            rank?: number;
            matchType?: string;
            verificationStatus?: string;
            dedupeKey?: string;
        };
        TranscriptSearchResponse: {
            /** Format: int64 */
            meetingId: number;
            query: string;
            normalizedQuery?: string;
            transcriptMode?: string;
            canonicalTranscriptHash?: string | null;
            canonicalTranscriptVersion?: string | null;
            matches: components["schemas"]["TranscriptEvidenceMatch"][];
        };
        ActionPlanResponse: {
            meeting?: {
                [key: string]: unknown;
            };
            actionItems?: ({
                task?: string;
                evidence?: components["schemas"]["TranscriptEvidenceMatch"];
            } & {
                [key: string]: unknown;
            })[];
            groupedActionPlan?: {
                [key: string]: unknown;
            };
            analysisMetadata?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        TechnicalTerm: {
            term: string;
            meaning: string;
            category: string;
        };
        PainPoint: {
            title: string;
            evidence: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high";
        };
        MeetingChatResponse: {
            /** Format: int64 */
            meetingId?: number;
            answer?: string;
            provider?: string;
            source_segments?: components["schemas"]["TranscriptEvidenceMatch"][];
        };
        SemanticSearchResponse: {
            query?: string;
            provider?: string;
            results?: {
                [key: string]: unknown;
            }[];
        };
        CrossMeetingAskResponse: {
            question?: string;
            answer?: string;
            provider?: string;
            meetings?: {
                [key: string]: unknown;
            }[];
        };
        /** @enum {string} */
        StudyArtifactType: "MIND_MAP" | "FLASHCARDS" | "MULTIPLE_CHOICE" | "ESSAY_QUESTIONS" | "EXAM_BRIEF";
        /** @enum {string} */
        SourceSelectionMode: "ALL_READY" | "EXPLICIT";
        /** @enum {string} */
        StudyJobStatus: "QUEUED" | "PROCESSING" | "COMPLETED" | "FAILED" | "STALE" | "QUOTA_EXCEEDED" | "PARTIALLY_FAILED";
        SubjectSynthesisRequest: {
            meetingIds?: number[];
            language?: string;
            sourceSelectionMode?: components["schemas"]["SourceSelectionMode"];
        };
        /** @enum {string} */
        QuotaConsumeStatus: "ALLOWED" | "DENIED" | "UNKNOWN";
        StudyQuotaItemDetail: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            artifactId?: number;
            quotaStatus?: components["schemas"]["QuotaConsumeStatus"];
            idempotencyKey?: string;
            /** @enum {string} */
            quotaType?: "SUBJECT_SYNTHESIS" | "STUDY_ARTIFACT";
            errorCode?: string | null;
            retryable?: boolean;
            status?: components["schemas"]["StudyJobStatus"];
            dispatchStatus?: string | null;
        } & {
            [key: string]: unknown;
        };
        SubjectSynthesisResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            subjectId?: number;
            status?: components["schemas"]["StudyJobStatus"];
            version?: number;
            cacheHit?: boolean;
            stale?: boolean;
            sourceMeetingIds?: number[];
            content?: {
                [key: string]: unknown;
            } | null;
            partialQuota?: boolean;
            quotaDetails?: components["schemas"]["StudyQuotaItemDetail"][];
        } & {
            [key: string]: unknown;
        };
        StudyArtifactsRequest: {
            /** Format: int64 */
            subjectId: number;
            meetingIds?: number[];
            artifactTypes: components["schemas"]["StudyArtifactType"][];
            sourceSelectionMode?: components["schemas"]["SourceSelectionMode"];
            options?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            synthesisId?: number | null;
        };
        StudyArtifactResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            subjectId?: number;
            artifactType?: components["schemas"]["StudyArtifactType"];
            status?: components["schemas"]["StudyJobStatus"];
            version?: number;
            cacheHit?: boolean;
            stale?: boolean;
            content?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        StudyArtifactsResponse: {
            artifactIds?: number[];
            newlyCreatedArtifactIds?: number[];
            cacheHitArtifactIds?: number[];
            inFlightArtifactIds?: number[];
            status?: components["schemas"]["StudyJobStatus"];
            partialQuota?: boolean;
            quotaDetails?: components["schemas"]["StudyQuotaItemDetail"][];
            artifacts?: components["schemas"]["StudyArtifactResponse"][];
        } & {
            [key: string]: unknown;
        };
        StudyArtifactsListResponse: {
            items?: components["schemas"]["StudyArtifactResponse"][];
            status?: components["schemas"]["StudyJobStatus"];
            page?: number;
            size?: number;
            /** Format: int64 */
            total?: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded file metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
        };
    };
    startProcessing: {
        parameters: {
            query?: {
                meetingId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProcessStartRequest"];
            };
        };
        responses: {
            /** @description Processing status after enqueue/start */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingStartResponse"];
                };
            };
        };
    };
    getProcessingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processing status payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingStatusResponse"];
                };
            };
        };
    };
    getProcessingTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcript payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPayload"];
                };
            };
        };
    };
    getProcessingAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisPayload"];
                };
            };
        };
    };
    exportRawTranscript: {
        parameters: {
            query: {
                format: "txt" | "csv";
                mode?: "readable" | "raw";
            };
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcript export payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "text/csv": string;
                };
            };
        };
    };
    getMeetingTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcript payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPayload"];
                };
            };
        };
    };
    searchMeetingTranscriptEvidence: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                context?: number;
            };
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcript search response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSearchResponse"];
                };
            };
        };
    };
    askMeetingChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                };
            };
        };
        responses: {
            /** @description Chat response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingChatResponse"];
                };
            };
        };
    };
    semanticSearchMeetings: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                };
            };
        };
        responses: {
            /** @description Semantic search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSearchResponse"];
                };
            };
        };
    };
    askCrossMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                    limit?: number;
                };
            };
        };
        responses: {
            /** @description Cross-meeting answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossMeetingAskResponse"];
                };
            };
        };
    };
    getMeetingActionPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Action plan preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPlanResponse"];
                };
            };
        };
    };
    exportMeetingActionPlan: {
        parameters: {
            query?: {
                format?: "docx" | "pdf";
            };
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Action plan export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    "application/pdf": string;
                };
            };
        };
    };
    exportMeetingReport: {
        parameters: {
            query?: {
                format?: "docx" | "pdf";
            };
            header?: never;
            path: {
                meetingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting report export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    "application/pdf": string;
                };
            };
        };
    };
    getSubjectSynthesis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current synthesis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectSynthesisResponse"];
                };
            };
        };
    };
    createSubjectSynthesis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubjectSynthesisRequest"];
            };
        };
        responses: {
            /** @description Synthesis job or cache hit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectSynthesisResponse"];
                };
            };
        };
    };
    getSubjectSynthesisStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synthesis status payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectSynthesisResponse"];
                };
            };
        };
    };
    regenerateSubjectSynthesis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubjectSynthesisRequest"];
            };
        };
        responses: {
            /** @description New synthesis version queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectSynthesisResponse"];
                };
            };
        };
    };
    createStudyArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyArtifactsRequest"];
            };
        };
        responses: {
            /** @description Artifact prepare response with ids and statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyArtifactsResponse"];
                };
            };
        };
    };
    getStudyArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifactId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Study artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyArtifactResponse"];
                };
            };
        };
    };
    deleteStudyArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifactId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    regenerateStudyArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifactId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regenerated artifact batch response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyArtifactsResponse"];
                };
            };
        };
    };
    listSubjectStudyArtifacts: {
        parameters: {
            query?: {
                artifactType?: components["schemas"]["StudyArtifactType"];
                status?: string;
                page?: number;
                size?: number;
                sort?: "updated_at_desc" | "created_at_desc" | "version_desc";
            };
            header?: never;
            path: {
                subjectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyArtifactsListResponse"];
                };
            };
        };
    };
    getTranscriptQualityPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcript quality policy JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createProcessingJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Job processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
}
