from typing import Any, Callable

import httpx
from loguru import logger

from app.services.ai_analyzer import AIAnalyzer
from app.services.analysis_errors import AnalysisConfigError, AnalysisParseError


class GeminiAnalyzer(AIAnalyzer):
    def __init__(
        self,
        api_key: str,
        analysis_model: str = "gemini-3.1-flash-lite",
        summary_model: str = "gemini-3.1-flash-lite",
        analysis_domain_mode: str = "it",
        analysis_max_input_tokens: int = 12000,
        analysis_max_output_tokens: int = 4096,
        analysis_thinking_budget: int | None = 0,
        thinking_level: str = "low",
        temperature: float = 0.2,
        chat_max_output_tokens: int = 1200,
        summary_max_output_tokens: int = 2048,
        structured_analysis_max_output_tokens: int | None = None,
        study_artifact_max_output_tokens: int = 3072,
        analysis_retry_max_attempts: int = 2,
        gemini_rate_limit_retry_base_seconds: float = 30.0,
        gemini_rate_limit_retry_max_seconds: float = 90.0,
        gemini_retry_quota_exceeded: bool = False,
        gemini_max_tokens_retry_enabled: bool = True,
        gemini_max_single_request_chars: int = 50000,
        gemini_request_delay_seconds: float = 15.0,
        gemini_api_keys: str = "",
        gemini_multi_key_enabled: bool = False,
        gemini_max_attempts: int = 2,
        gemini_max_schema_retries: int = 1,
        gemini_max_token_retries: int = 1,
        gemini_key_project_groups: str = "",
        gemini_cross_project_failover_enabled: bool = False,
        gemini_key_cooldown_seconds: float = 90.0,
        gemini_key_hard_cooldown_seconds: float = 900.0,
        gemini_backoff_base_ms: float = 500.0,
        gemini_backoff_max_ms: float = 10000.0,
        gemini_backoff_jitter: bool = True,
        gemini_fail_fast_seconds: float = 30.0,
        gemini_model_fallbacks: str = "gemini-2.0-flash,gemini-2.5-flash-lite",
        timeout_seconds: int = 300,
        http_client_factory: Callable[..., Any] | None = None,
    ):
        super().__init__(
            api_key=api_key,
            model=analysis_model,
            provider="gemini",
            summary_model=summary_model,
            analysis_domain_mode=analysis_domain_mode,
            analysis_max_input_tokens=analysis_max_input_tokens,
            analysis_max_output_tokens=analysis_max_output_tokens,
            analysis_thinking_budget=analysis_thinking_budget,
            thinking_level=thinking_level,
            temperature=temperature,
            chat_max_output_tokens=chat_max_output_tokens,
            summary_max_output_tokens=summary_max_output_tokens,
            structured_analysis_max_output_tokens=structured_analysis_max_output_tokens,
            study_artifact_max_output_tokens=study_artifact_max_output_tokens,
            analysis_retry_max_attempts=analysis_retry_max_attempts,
            gemini_rate_limit_retry_base_seconds=gemini_rate_limit_retry_base_seconds,
            gemini_rate_limit_retry_max_seconds=gemini_rate_limit_retry_max_seconds,
            gemini_retry_quota_exceeded=gemini_retry_quota_exceeded,
            gemini_max_tokens_retry_enabled=gemini_max_tokens_retry_enabled,
            gemini_max_single_request_chars=gemini_max_single_request_chars,
            gemini_request_delay_seconds=gemini_request_delay_seconds,
            gemini_api_keys=gemini_api_keys,
            gemini_multi_key_enabled=gemini_multi_key_enabled,
            gemini_max_attempts=gemini_max_attempts,
            gemini_max_schema_retries=gemini_max_schema_retries,
            gemini_max_token_retries=gemini_max_token_retries,
            gemini_key_project_groups=gemini_key_project_groups,
            gemini_cross_project_failover_enabled=gemini_cross_project_failover_enabled,
            gemini_key_cooldown_seconds=gemini_key_cooldown_seconds,
            gemini_key_hard_cooldown_seconds=gemini_key_hard_cooldown_seconds,
            gemini_backoff_base_ms=gemini_backoff_base_ms,
            gemini_backoff_max_ms=gemini_backoff_max_ms,
            gemini_backoff_jitter=gemini_backoff_jitter,
            gemini_fail_fast_seconds=gemini_fail_fast_seconds,
            gemini_model_fallbacks=gemini_model_fallbacks,
            timeout_seconds=timeout_seconds,
            http_client_factory=http_client_factory,
        )


__all__ = [
    "GeminiAnalyzer",
    "logger",
    "httpx",
    "AnalysisConfigError",
    "AnalysisParseError",
]
