apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - audiomind
  selector:
    matchLabels:
      app: user-api
      monitoring: "enabled"
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
