apiVersion: v1
kind: Service
metadata:
  name: meeting-api
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: meeting-api
spec:
  selector:
    app: meeting-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: processing-api
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: processing-api
spec:
  selector:
    app: processing-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: user-api
spec:
  selector:
    app: user-api
  ports:
    - name: http
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: ai-api
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: ai-api
spec:
  selector:
    app: ai-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: whisper-service
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: whisper-service
spec:
  selector:
    app: whisper-service
  ports:
    - name: http
      port: 8011
      targetPort: 8011
---
apiVersion: v1
kind: Service
metadata:
  name: diarization-service
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: diarization-service
spec:
  selector:
    app: diarization-service
  ports:
    - name: http
      port: 8012
      targetPort: 8012
---
apiVersion: v1
kind: Service
metadata:
  name: ai-processing-service
  namespace: audiomind
  labels:
    monitoring: "enabled"
    app: ai-processing-service
spec:
  selector:
    app: ai-processing-service
  ports:
    - name: http
      port: 8010
      targetPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: audiomind
spec:
  selector:
    app: ollama-service
  ports:
    - name: http
      port: 11434
      targetPort: 11434
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: audiomind
spec:
  selector:
    app: db
  ports:
    - name: db
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: audiomind
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
