apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-api-deployment
  namespace: audiomind
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-api-deployment
  namespace: audiomind
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api-deployment
  namespace: audiomind
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-processing-service-deployment
  namespace: audiomind
spec:
  replicas: 2
