apiVersion: v1
kind: Secret
metadata:
  name: audiomind-secrets
  namespace: audiomind-staging
type: Opaque
stringData:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  DATABASE_URL: ""
  USER_JWT_SECRET: ""
  GF_SECURITY_ADMIN_USER: ""
  GF_SECURITY_ADMIN_PASSWORD: ""
  HUGGINGFACE_TOKEN: ""
